### ISSUE TITLE
`OptimizeOptions` are not exported from `svgo`

### ISSUE THREAD

**Issue by ivancuric** [jfgodoy/vite-plugin-solid-svg#30]
Looking at 
```
node_modules/.pnpm/vite-plugin-solid-svg@0.6.2_solid-js@1.7.6_vite@4.3.9/node_modules/vite-plugin-solid-svg/dist/index.d.ts
```
you can see that `OptimizeOptions` aren't exported: `Could not find a declaration file for module 'svgo'.`

Installing `svgo` installs the latest version but `OptimizeOptions` aren't available there as well.

**Comment by jfgodoy** [comment]
hi @ivancuric!! thank you very much for the report. You're right, the type inference for the svgo isn't working properly. The project still has `svgo@2`, so installing `@types/svgo@2` should add the types. The problem was that `@types/svgo@2`  is listed in devDependencies instead of `dependencies`. I will publish a fix for that.

**Comment by jfgodoy** [comment]
published as 0.6.3. 
I will update the deps soon.

**Comment by jfgodoy** [comment]
Sorry for the delay.
The dependencies are now up to date.

**Comment by SploxFox** [comment]
@jfgodoy I am still getting this error on the latest version, and installing `@types/svgo@2` doesn't seem to work either.

**Comment by Cavitedev** [comment]
I have this same issue on version 0.7.0

**Comment by jfgodoy** [comment]
I'm not entirely sure what you're asking for. Could you please check version 0.8.0? From a new project, I'm able to have type inference for the svgo config.
![image](https://github.com/jfgodoy/vite-plugin-solid-svg/assets/731635/dd40ec3d-2024-4349-873e-4638f66bb09d)
