### ISSUE TITLE
cannot find module vite-plugin-solid-svg types in vite.config.ts

### ISSUE THREAD

**Issue by xieccc** [jfgodoy/vite-plugin-solid-svg#46]
cannot find module vite-plugin-solid-svg types in vite.config.ts

**Comment by jfgodoy** [comment]
hi @xieccc!
which moduleResolution are you using in your tsconfig?. Should be different from node/node10.

**Comment by xieccc** [comment]
Hi @jfgodoy 
I found that the value for moduleResolution in my project tsconfig file is node, and I change it to bundler.
Now it can be run normally.
Thank you.

**Comment by syirilrakhulh** [comment]
Hi, after I change to bundler it's still error in my VSCode, but still running perfectly. Maybe because I use NX monorepo?


`import { defineConfig } from "vite";
import solidPlugin from "vite-plugin-solid";
import { nxViteTsPaths } from "@nx/vite/plugins/nx-tsconfig-paths.plugin";
import solidSVG from "vite-plugin-solid-svg";

export default defineConfig({
  root: __dirname,
  cacheDir: "../../node_modules/.vite/libs/design-system",
  server: {
    port: 4200,
    host: "localhost"
  },
  preview: {
    port: 4300,
    host: "localhost"
  },
  plugins: [solidPlugin(), solidSVG({ defaultAsComponent: true }), nxViteTsPaths()],
  // Uncomment this if you are using workers.
  // worker: {
  //  plugins: [ nxViteTsPaths() ],
  // },
  build: {
    outDir: "../../dist/libs/design-system",
    reportCompressedSize: true,
    commonjsOptions: {
      transformMixedEsModules: true
    }
  }
});
`

**Comment by jfgodoy** [comment]
hi @syirilrakhulh, I'm not familiarized with Nx Monorepo, but if you provide a minimal repo I could figure out what's going on
