### ISSUE TITLE
version 0.8.0

### ISSUE THREAD

**Issue by literalpie** [jfgodoy/vite-plugin-solid-svg#49]
Hi, I noticed that v0.8.0 is the latest version according to `npm info vite-plugin-solid-svg`, but v0.7.0 is the latest according to the changelog and the main branch.

Also, TS is unable to find the appropriate types in v0.8.0 because in package.json `exports['.'].types` doesn't exist.

I'm not sure if 0.8.0 is an unintentional/unsupported release, or if the main branch of this repo is somehow out of date. Either way, I think something is off here.

**Comment by jfgodoy** [comment]
Thank you very much,
I forgot to push the latest changes.

The types are working for Node 16 ESM and bundler. I don't know how to make all of them work, so I fixed the modern ones instead of the older ones. If you can help me, PRs are welcome.
![image](https://github.com/jfgodoy/vite-plugin-solid-svg/assets/731635/71bdb304-de5d-43fb-92bd-8caa4151c19b)
source: https://arethetypeswrong.github.io/?p=vite-plugin-solid-svg%400.8.0
